ignore_colors = [
	[0, 0, 0, 0],
	# [0, 0, 0, 255], # filter all black
]

# priority: higher number = higher chance of being placed

version = 16

[priorities]
"0" = 0
"1" = 1
"2" = 5
"3" = 10

[[structure]]
name = "domo"
file = "images/domo.png"
startx = 1345 #x-Koordinate
starty = 1784 #y-Koordinate
priority = 2

[[structure]]
name = "socki"
file = "images/socki.jpg"
startx = 1315 #x-Koordinate
starty = 1783 #y-Koordinate
priority = 2